### ISSUE TITLE
Cannot access the gateway when using kind

### ISSUE THREAD

**Issue by veggiemonk** [openfaas-incubator/openfaas-linkerd2#5]
When using faas-netes, here are the steps to reproduce:
 
```bash
$ make start-kind
...
[kind started and faas-netes installed]

$ linkerd install --proxy-auto-inject | kubectl apply -f -

$ linkerd check # make sure it is installed

$ linkerd dashboard & # I can see the dashboard

$ faas-cli invoke echo 

[can't reach gateway]
```

I'm using "Docker for Mac".
Any idea ?

**Comment by alexellis** [comment]
Good question.

@matipan could you look into this?

**Comment by alexellis** [comment]
What gateway address are you using in `faas-cli invoke`? Can you provide the actual output from the CLI?

You should port-forward the gateway if you want to access it ( I think the script does that, but you'll also need to set `OPENFAAS_URL` or use `--gateway`. )

**Comment by veggiemonk** [comment]
Thanks @alexellis,

Port-forwarding solved it.
